version: '3'

services:
  db:
    image: mysql:latest
    container_name: db_skeletonSpringboot
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: elakatos
      MYSQL_USER: user
      MYSQL_PASSWORD: userpw
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma_skeletonSpringboot
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    restart: always
    ports:
      - "80:80"

volumes:
  data:
